server:
  port: 3001
  
spring:
  application:
    name: zuul
#关闭配置文件的覆盖
  cloud:
    config:
      override-none: true    
  
eureka:  client:    service-url:      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
zuul:  routes:
  #有默认配置的  如果服务名叫做 item-service则配置为 /item-service/**下的所有路径进行拦截   item-service: /item-service/**
   user-service: /user-service/**
   order-service: /order-service/**
   
#默认值 0 1 1000 1000
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#  MaxAutoRetriesNextServer: 1
#  MaxAutoRetries: 1

#配置  降级等待超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 700